CREATE TABLE IF NOT EXISTS mood_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
    label TEXT,
    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
